# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20170610_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
        ),
    ]
