# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20170611_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='share_message',
            field=models.TextField(default='\ncheck out this video\n'),
        ),
    ]
