# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_share_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='share_message',
            field=models.TextField(default='check out this video'),
        ),
    ]
