# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20170613_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title', 'timestamp']},
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.SlugField(choices=[('ghanawood', 'ghanawood'), ('nollywood', 'nollywood'), ('music', 'music'), ('entertainment', 'entertainment')]),
        ),
    ]
