# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20170614_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', '-timestamp']},
        ),
    ]
