# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_auto_20170624_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
