# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_auto_20170630_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='share_message',
            field=models.CharField(default='check out this video', max_length=500),
        ),
    ]
