# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 04:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20170614_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMecrhantId',
            new_name='UserMerchantId',
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 4, 41, 19, 325877, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 4, 41, 19, 325905, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
