# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20170614_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermerchantid',
            old_name='mecrhant_name',
            new_name='merchant_name',
        ),
        migrations.AddField(
            model_name='usermerchantid',
            name='plan_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='usermerchantid',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 20, 6, 7, 319266, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 20, 6, 7, 319294, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
