# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20170616_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 25, 4, 46, 46, 466777, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 25, 4, 46, 46, 466817, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
