# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20170625_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 8, 46, 34, 561716, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 8, 46, 34, 561756, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
