# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20170626_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 10, 52, 9, 13923, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 10, 52, 9, 13964, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
