# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 00:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0040_auto_20170630_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 1, 0, 13, 25, 617032, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 1, 0, 13, 25, 617073, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
