# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0041_auto_20170630_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 1, 0, 15, 4, 820312, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 1, 0, 15, 4, 820353, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
