# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0046_auto_20170702_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 2, 13, 38, 15, 19372, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 2, 13, 38, 15, 19413, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
