# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2017, 6, 14, 10, 43, 44, 954781, tzinfo=utc)),
        ),
    ]
