# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20170614_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 20, 11, 7, 351501, tzinfo=utc)),
        ),
    ]
