# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 01:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20170615_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 1, 58, 27, 46793, tzinfo=utc)),
        ),
    ]
