# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_auto_20170616_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 25, 4, 46, 46, 387228, tzinfo=utc)),
        ),
    ]
