# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_auto_20170625_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 3, 38, 30, 685845, tzinfo=utc)),
        ),
    ]
