# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_auto_20170626_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 9, 5, 20, 698799, tzinfo=utc)),
        ),
    ]
