# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_auto_20170626_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 10, 57, 29, 25292, tzinfo=utc)),
        ),
    ]
