# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0044_auto_20170630_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 18, 33, 59, 98399, tzinfo=utc)),
        ),
    ]
