# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0047_auto_20170630_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 1, 0, 15, 4, 736709, tzinfo=utc)),
        ),
    ]
