# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0049_auto_20170630_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 1, 2, 16, 3, 888541, tzinfo=utc)),
        ),
    ]
