# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0050_auto_20170630_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 2, 8, 47, 24, 248344, tzinfo=utc)),
        ),
    ]
