# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 23:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(default=datetime.datetime(2017, 6, 14, 23, 35, 48, 19513, tzinfo=utc))),
                ('date_start', models.DateTimeField(default=datetime.datetime(2017, 6, 14, 23, 35, 48, 19546, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
