# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import series.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=series.fields.PositionField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
