# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_auto_20170630_1159'),
        ('categories', '0002_auto_20170630_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
    ]
