# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_auto_20170624_2247'),
        ('series', '0002_series_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('share_message', models.TextField(default='Check out this African Series')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='series',
            name='active',
        ),
        migrations.RemoveField(
            model_name='series',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='series',
            name='free_preview',
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.Series'),
        ),
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.Video'),
        ),
    ]
