# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:57
from __future__ import unicode_literals

from django.db import migrations
import series.fields


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_auto_20170626_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='order',
            field=series.fields.PositionField(default=-1),
        ),
    ]
