# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_auto_20170626_0457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['order', 'title']},
        ),
    ]
