# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:07
from __future__ import unicode_literals

from django.db import migrations
import series.fields


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0011_auto_20170626_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='order',
            field=series.fields.PositionField(default=-1),
        ),
    ]
