# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0012_series_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.CharField(choices=[('main', 'Main'), ('sec', 'Secondary')], default='main', max_length=120),
        ),
    ]
