# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0014_myseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myseries',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
