# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0015_auto_20170628_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myseries',
            options={'verbose_name': 'My series', 'verbose_name_plural': 'My series'},
        ),
        migrations.AlterField(
            model_name='myseries',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='watched', to='series.Series'),
        ),
    ]
