# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170630_0335'),
        ('series', '0018_auto_20170629_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='category',
        ),
        migrations.AddField(
            model_name='series',
            name='categor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_category', to='categories.Category'),
        ),
    ]
