# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0019_auto_20170630_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='categor',
            new_name='category',
        ),
    ]
