# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0020_auto_20170630_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='share_message',
            field=models.CharField(default='Check out this African Series', max_length=250),
        ),
    ]
