# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170630_0335'),
        ('series', '0021_auto_20170630_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='secondary_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='secondary_category', to='categories.Category'),
        ),
    ]
