# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import series.models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0023_auto_20170630_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(height_field=models.IntegerField(blank=True, null=True), null=True, upload_to=series.models.handle_upload, width_field=models.IntegerField(blank=True, null=True)),
        ),
        migrations.AddField(
            model_name='series',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
