# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0025_auto_20170630_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='free_preview',
            field=models.BooleanField(default=False),
        ),
    ]
