# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0026_episode_free_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='secondary_category',
            new_name='secondary',
        ),
    ]
